version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  buildAndDeploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version " 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            echo "Installing dependencies in the the backend API  "
            npm run api:install
      - run:
          name: Front-End Lint
          command: |
            echo "Linting the frontend"
            npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            echo "Building the frontend app"
            npm run frontend:build
      - run:
          name: API Build
          command: |
            echo "Building the backend API"
            npm run api:build
      - run:
          name: Deploy App
          command: |
            echo "Deploying FE and BE"
            npm run deploy
      - run:
          name: setEnv
          command: |
            echo "setenv"
            npm run setenv
workflows:
  udagram:
    jobs:
      - buildAndDeploy:
          filters:
            branches:
              only:
                - main
